apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ray-cluster.fullname" . }}-head
spec:
  replicas: {{ .Values.rayHead.replicas }}
  selector:
    matchLabels:
      app: {{ include "ray-cluster.fullname" . }}
      component: head
  template:
    metadata:
      labels:
        app: {{ include "ray-cluster.fullname" . }}
        component: head
    spec:
      containers:
      - name: ray-head
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["ray", "start", "--head", "--port=6379"]
        resources:
          {{- toYaml .Values.rayHead.resources | nindent 10 }}
