apiVersion: v1
kind: Service
metadata:
  name: {{ include "ray-cluster.fullname" . }}-head
spec:
  type: {{ .Values.rayHead.serviceType }}
  ports:
    - port: 6379
      targetPort: 6379
      name: client
  selector:
    app: {{ include "ray-cluster.fullname" . }}
    component: head
